---
- name: Install httpd
  ansible.builtin.dnf:
    name: 
      - httpd
      - firewalld
    state: present


- name: Start and enable httpd
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: started

- name: Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: true
    state: started 

- name: Add firewalld rules
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled

- name: Create page content
  ansible.builtin.template:
    src: template.j2
    dest: /var/www/html/index.html

    

